const partners = [
  {
    id: "1",
    name: "AutoService Pro",
    fullName: "AutoService Professional Center",
    description: "Профессиональный автосервис с 15-летним опытом",
    phoneNumber: "+7 (999) 123-45-67",
    address: "ул. Автомобильная, 15",
    averageRating: 4.9,
    totalReviews: 523,
    isOpen: true,
    maxCarsPerDay: 20,
    hasParking: true,
    hasWaitingRoom: true,
    venues: [
      {
        name: "Основной цех",
        address: "ул. Автомобильная, 15",
        phoneNumber: "+7 (999) 123-45-67",
        email: "main@autoservice.pro",
        isOpen: true,
        latitude: 55.7558,
        longitude: 37.6173,
        services: [
          {
            name: "Диагностика двигателя",
            description: "Комплексная диагностика двигателя",
            price: 2000,
            duration: "01:00:00",
            isActive: true,
            rating: 4.9,
          },
          {
            name: "Замена масла",
            description: "Замена масла и фильтров",
            price: 1500,
            duration: "00:30:00",
            isActive: true,
            rating: 4.8,
          },
        ],
      },
    ],
    workingHours: [
      {
        day: "Monday",
        isDayOff: false,
        openTime: "09:00:00",
        closeTime: "20:00:00",
      },
      {
        day: "Sunday",
        isDayOff: true,
        openTime: "00:00:00",
        closeTime: "00:00:00",
      },
    ],
  },
  {
    id: "2",
    name: "CarTech",
    fullName: "CarTech Auto Service",
    description: "Современный автосервис с новейшим оборудованием",
    phoneNumber: "+7 (999) 234-56-78",
    address: "пр. Технический, 42",
    averageRating: 4.8,
    totalReviews: 312,
    isOpen: true,
    maxCarsPerDay: 15,
    hasParking: true,
    hasWaitingRoom: true,
    venues: [
      {
        name: "Технический центр",
        address: "пр. Технический, 42",
        phoneNumber: "+7 (999) 234-56-78",
        email: "service@cartech.ru",
        isOpen: true,
        latitude: 55.7658,
        longitude: 37.6273,
        services: [
          {
            name: "Компьютерная диагностика",
            description: "Диагностика электронных систем",
            price: 2500,
            duration: "01:30:00",
            isActive: true,
            rating: 4.8,
          },
          {
            name: "Ремонт подвески",
            description: "Диагностика и ремонт подвески",
            price: 3000,
            duration: "02:00:00",
            isActive: true,
            rating: 4.7,
          },
        ],
      },
    ],
    workingHours: [
      {
        day: "Monday",
        isDayOff: false,
        openTime: "08:00:00",
        closeTime: "21:00:00",
      },
      {
        day: "Sunday",
        isDayOff: true,
        openTime: "00:00:00",
        closeTime: "00:00:00",
      },
    ],
  },
  {
    id: "3",
    name: "AutoElite",
    fullName: "AutoElite Premium Service",
    description: "Премиальный автосервис для люксовых автомобилей",
    phoneNumber: "+7 (999) 345-67-89",
    address: "ул. Премиум, 7",
    averageRating: 4.9,
    totalReviews: 428,
    isOpen: true,
    maxCarsPerDay: 10,
    hasParking: true,
    hasWaitingRoom: true,
    venues: [
      {
        name: "Премиум-центр",
        address: "ул. Премиум, 7",
        phoneNumber: "+7 (999) 345-67-89",
        email: "premium@autoelite.ru",
        isOpen: true,
        latitude: 55.7758,
        longitude: 37.6373,
        services: [
          {
            name: "Премиум-диагностика",
            description: "Расширенная диагностика премиум-автомобилей",
            price: 5000,
            duration: "02:00:00",
            isActive: true,
            rating: 4.9,
          },
          {
            name: "Обслуживание премиум",
            description: "Комплексное обслуживание премиум-автомобилей",
            price: 8000,
            duration: "03:00:00",
            isActive: true,
            rating: 4.9,
          },
        ],
      },
    ],
    workingHours: [
      {
        day: "Monday",
        isDayOff: false,
        openTime: "10:00:00",
        closeTime: "22:00:00",
      },
      {
        day: "Sunday",
        isDayOff: true,
        openTime: "00:00:00",
        closeTime: "00:00:00",
      },
    ],
  },
  {
    id: "4",
    name: "QuickFix",
    fullName: "QuickFix Express Service",
    description: "Быстрый автосервис для срочного ремонта",
    phoneNumber: "+7 (999) 456-78-90",
    address: "ул. Быстрая, 25",
    averageRating: 4.7,
    totalReviews: 215,
    isOpen: true,
    maxCarsPerDay: 30,
    hasParking: true,
    hasWaitingRoom: true,
    venues: [
      {
        name: "Экспресс-центр",
        address: "ул. Быстрая, 25",
        phoneNumber: "+7 (999) 456-78-90",
        email: "express@quickfix.ru",
        isOpen: true,
        latitude: 55.7858,
        longitude: 37.6473,
        services: [
          {
            name: "Экспресс-диагностика",
            description: "Быстрая диагностика основных систем",
            price: 1500,
            duration: "00:30:00",
            isActive: true,
            rating: 4.7,
          },
          {
            name: "Срочный ремонт",
            description: "Быстрый ремонт неисправностей",
            price: 3000,
            duration: "01:00:00",
            isActive: true,
            rating: 4.6,
          },
        ],
      },
    ],
    workingHours: [
      {
        day: "Monday",
        isDayOff: false,
        openTime: "07:00:00",
        closeTime: "23:00:00",
      },
      {
        day: "Sunday",
        isDayOff: false,
        openTime: "09:00:00",
        closeTime: "21:00:00",
      },
    ],
  },
];
